### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by jrchamp** [srguglielmo/SimpleShib#1]
Hi @srguglielmo ! This looks like a nice, straightforward Shibboleth plugin. I think you have a lot of the basics done right, but to make this work for a variety of setups it would be helpful to have a lot of these options be configurable.

Please consider taking a look at the configuration interface and pull requests like mitcho/shibboleth#13. Those give a quick overview of the needs of we've seen on different server setups.

**Comment by srguglielmo** [comment]
Hey @jrchamp.

Thanks for the feedback!

I did not initially intend for this to be released to the public, so the feature set is limited to my own infrastructure at the moment. However, since I received permission from my employer to release it publicly, I'm more than happy to start adding features that will be useful to the majority of users.

I decided early on that I didn't want to have a configuration UI within WordPress for a few reasons:

- More code to maintain; the plugin becomes more complex (I'm a sysadmin, not a dev).
- It's a safe assumption that if someone is setting up Shibboleth, then they know how to edit a text file on a server.
- For something like this, the settings are generally _set and forget_. Once initially tested and configured, settings should rarely be changed.

However, I'll take a look at the [other shib plugin](https://wordpress.org/plugins/shibboleth/)'s configuration options and the pending issues/pull requests over the next couple weeks and see what I can add. I'll split individual features into separate GitHub issues for tracking (instead of using this issue for all of them).

**Comment by jrchamp** [comment]
Thank you for taking this into consideration. Your plan to have individual features for tracking sounds great!

It is worth nothing that often these users are on shared servers that are configured for Shibboleth at the server level already, but do not have the ability to edit the file directly and are instead following instructions from a shared configuration document.

For me, the code itself is maintained in version control, but I have separate configurations for each instance. Having and maintaining local modifications to the code on each installation runs counter to our code deployment process.

Hopefully these two opposite ends of the spectrum are good examples to support a stored configuration.

**Comment by srguglielmo** [comment]
Makes sense - specifically the version control argument. I made an issue for it (it may be a bit lower priority though). I'll close out this one for now. Thanks!
